AWSTemplateFormatVersion: '2010-09-09'
Description: IaaC using CloudFormation

Parameters:

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH

  DBUsername:
    Type: String
    Default: admin

  DBPassword:
    Type: String
    NoEcho: true


Resources:

# ----------------------------
# VPC
# ----------------------------

  IaaCUsingAWSCFVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

# ----------------------------
# Internet Gateway
# ----------------------------

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref IaaCUsingAWSCFVPC
      InternetGatewayId: !Ref InternetGateway

# ----------------------------
# Subnets
# ----------------------------

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref IaaCUsingAWSCFVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  AppPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref IaaCUsingAWSCFVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']

  DBPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref IaaCUsingAWSCFVPC
      CidrBlock: 10.0.3.0/24

# ----------------------------
# Route Table
# ----------------------------

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref IaaCUsingAWSCFVPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRoute:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

# ----------------------------
# Security Groups
# ----------------------------

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref IaaCUsingAWSCFVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  AppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH from Web Tier
      VpcId: !Ref IaaCUsingAWSCFVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          SourceSecurityGroupId: !Ref WebSG

  DBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from App Tier
      VpcId: !Ref IaaCUsingAWSCFVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppSG

# ----------------------------
# Web Tier EC2
# ----------------------------

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebSG
      KeyName: !Ref KeyPairName
      ImageId: ami-02dfbd4ff395f2a1b

# ----------------------------
# Application Tier EC2
# ----------------------------

  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SubnetId: !Ref AppPrivateSubnet
      SecurityGroupIds:
        - !Ref AppSG
      KeyName: !Ref KeyPairName
      ImageId: ami-02dfbd4ff395f2a1b

# ----------------------------
# DB Subnet Group
# ----------------------------

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group
      SubnetIds:
        - !Ref AppPrivateSubnet
        - !Ref DBPrivateSubnet

# ----------------------------
# RDS MYSQL
# ----------------------------

  MyDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: "20"
      VPCSecurityGroups:
        - !Ref DBSG
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false

# ----------------------------
# Route53 Hosted Zone
# ----------------------------

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: myxyzcorp.com

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: app.myxyzcorp.com
      Type: A
      TTL: "300"
      ResourceRecords:
        - !GetAtt WebServer.PublicIp
